services:
  obi-tracker:
    build: .
    image: obi-tracker:v2-multi  # 1. ERZWINGT ein komplett neues Image
    container_name: obi_tracker_v2 # 2. Neuer Container-Name gegen Zombies
    ports:
      - "5001:5000"  # 3. WICHTIG: Port auf 5001 geändert!
    volumes:
      - tracker_data:/app/data
    restart: unless-stopped

volumes:
  tracker_data:
