version: '3.8'

services:
  multitracker:
    build: .
    container_name: multitracker_app
    ports:
      - "5005:5000"
    volumes:
      # 1. Der Live-Mount: Lädt immer den neusten GitHub-Code in den Container!
      - ./:/app
      # 2. Das Daten-Volume: Schützt deine Screenshots und Keys vor dem Löschen
      - multitracker_data:/app/data
    restart: unless-stopped

volumes:
  multitracker_data:
